### ISSUE TITLE
[FEATURE] Allow positioning/removing the category's in the auction menu

### ISSUE THREAD

**Issue by Gfieldd** [Finally-A-Decent/Fadah#22]
**Is your feature request related to a problem? Please describe.**
On our server we aren't interested in having multiple categories set up yet, so we tried disabling them. This didn't work, so we opted for going for one all encompassing category instead, which is fine. But what we did want to do is remove the category items on the left side of the "main.yml" menu, in slots 9, 18, 27, and 36. To our surprise, these slots were already used by "FILLER" items, and the positioning of these category items isn't configurable.

**Describe the solution you'd like**
I think it would be nice if there was a layout option that would allow you to configure where the categories are shown, or in our case to decide to not to show them. Ideally these would be numbered, so it would be possible to configure in what direction the categories would be scrollable, in the case of having more categories than available slots. For our case this would not be needed though, and i would personally think an acceptable solution would be to load the categories into the slots based on numerical order of the slots. 
This would allow for more customization of the menu.

**Describe alternatives you've considered**
Because we just want to hide the option to select different categories, as we only have one and are going for a visually clean style, we have opted for having the category icon of our only category be a black stained glass pane, the same as the filler item, and have the same description and lack of name as the rest of the filler items to blend in. This is not a perfect solution, as the item can still be clicked and obtain the name " &eSELECTED", but for now we just called it an easter egg and went on with our day.

**Additional context**
![image](https://github.com/user-attachments/assets/dc986049-1302-4dce-bc4d-4049edd4f545)

**Comment by ProdPreva1l** [comment]
If you only want 1 category, you can remove all the categories and all the category items from the menu.

**Comment by Gfieldd** [comment]
If that is the intended behavior this might be a bug instead. If all of the categories are removed all of the items are indeed removed as well, but it only shows items that show up in a category on the auction menu, and it doesn't allow you to sell items that are not part of any categories

**Comment by ProdPreva1l** [comment]
Odd will look into it

**Comment by ProdPreva1l** [comment]
fixed https://github.com/Finally-A-Decent/Fadah/commit/788d4997349f379ab09b6d819220a79a218ec338
