### ISSUE TITLE
[BUG] Kicked due the legacy formatting

### ISSUE THREAD

**Issue by Taiyou06** [Finally-A-Decent/Fadah#23]
**Describe the bug**
I just clicked on the search button on the GUI and it kicked with the said message attached below.

**To Reproduce**
1. Click search icon
2. Get kicked

**Expected behavior**
You shouldn't be kicked lol

**Screenshots**
![image](https://github.com/user-attachments/assets/6c58c05c-b247-4da6-ac5a-490316d84ea0)
![image](https://github.com/user-attachments/assets/37160353-c890-45c8-83e4-03f315026c59)

**Environment (please complete the following information):**
 - OS: Linux
 - Server Type: Paper 
 - Server Version: 1.21.3
 - Plugin Version 2.7.3-HOTFIX

**Comment by ProdPreva1l** [comment]
Umm.... i just tested on the exact same setup. this is not an issue for me....

Could you please send the full stack trace

**Comment by Taiyou06** [comment]
![image](https://github.com/user-attachments/assets/37160353-c890-45c8-83e4-03f315026c59)
This is the full trace sadly, there isn't anything else other than this.

**Comment by ProdPreva1l** [comment]
Do you have any plugins that may interfere with gui titles? I just had a talk with the paper team and they see no reason for this to be happening.

**Comment by Taiyou06** [comment]
I have [Emojy](https://github.com/MineInAbyss/Emojy) if that counts as a plugin thats interfering with GUI titles?

**Comment by ProdPreva1l** [comment]
It does seem to touch anvils, you can try removing it. But this is just guessing

**Comment by ProdPreva1l** [comment]
didnt mean to close this whoops, lmk if you figure it out

**Comment by ProdPreva1l** [comment]
Gonna close as resolved as theres been no further issues
