### ISSUE TITLE
[BUG] When listing an item on the Auction House and then canceling it, the item is not returned to the player's inventory

### ISSUE THREAD

**Issue by Onism02** [Finally-A-Decent/Fadah#25]
**Describe the bug**
As described in the title, when an item is listed on the Auction House and the listing is canceled, the item is not returned to the player's inventory. It should stop being listed and return to the inventory upon cancellation
**To Reproduce**
1. listing item
2. Close menu

**Expected behavior**
The item should stop being listed and be returned to the player's inventory after canceling the listing.

**Screenshots**
![2024-12-23164628-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/da3d2c06-7ded-46fd-8ecf-807002367c71)

**Environment (please complete the following information):**
 - Windows 11
 - Server Type Mohist - 1.20.1-915, Java(61.0) 17.0.8
 - Server Version 1.20.1
 - Plugin Version 2.7.4

**Additional context**
none

**Comment by ProdPreva1l** [comment]
This is not a bug, the item is added to the expired listings

**Comment by Onism02** [comment]
![2024-12-23 165809](https://github.com/user-attachments/assets/21fb218e-1cfc-4a68-9fb9-34977f3a3e75)
Thanks for your reply but...

**Comment by ProdPreva1l** [comment]
Wait try collectionbox i couldve had that wrong, if its not there either ill take a look

**Comment by Onism02** [comment]
![2024-12-23 170127](https://github.com/user-attachments/assets/68cf2303-0d3e-4a61-b632-012387f3a8b5)
